### ISSUE TITLE
In-Game Editor Not Working

### ISSUE THREAD

**Issue by Construct-8** [PippleCultist/HoloCureCharacterCreatorMod#2]
The mod works mostly as intended, but when I go to export the character changes in the GUI, the game crashes and nothing is saved.

**Comment by Construct-8** [comment]
Sorry, as I sent this I figured it out. I used the MenuMod from the most recent Multiplayer update. I downloaded the one from the Character Creator and the menu is working fine now.

**Comment by PippleCultist** [comment]
I reuploaded the mod since it seems like the version number was incorrect for some reason. Can you try importing and exporting the example character to see if it also crashes? Also, if you press 'a' or 'd' while you're hovering over the skill trigger, it should cycle through the different options.

**Comment by Construct-8** [comment]
I downloaded the update, and it still crashes when exporting my character. Curious enough it doesn't crash when exporting the test character. I even tried deleting all images that aren't being used by the character, bit it still crashes.

The log still just says this:

2024_10_22_18_28_01 Holocure Character Creator Mod v1.0.2 - Finished initializing
2024_10_22_18_28_01 Holocure Menu Mod v1.0.1 - Finished initializing
2024_10_22_18_28_04 Holocure Character Creator Mod v1.0.2 - Loading char_zero

This is what the crash window looks like:
![image](https://github.com/user-attachments/assets/0eb32569-d6f5-4bc9-b803-c7488e36caa9)

**Comment by PippleCultist** [comment]
Can you send your character data?

**Comment by Construct-8** [comment]
[charData.json](https://github.com/user-attachments/files/17483186/charData.json)

**Comment by PippleCultist** [comment]
It's crashing because you set the charName to Zero which doesn't match your directory name char_zero. I'll work on fixing it, but you can change the capitalization of either one of those to match the other to fix it.

**Comment by Construct-8** [comment]
Definitely wasn't expecting that to be the defining factor. Thank you for the help!
