### ISSUE TITLE
Crash when onTakeDamage

### ISSUE THREAD

**Issue by Construct-8** [PippleCultist/HoloCureCharacterCreatorMod#3]
I've tried various combinations of activations and buffs. I can activate the buff through other methods, but for some reason if I take damage with a skill that procs a buff with onTakeDamage, the game immediately crashes. It doesn't require the buff to even strictly activate, because it crashes 100% of the time, despite the skill having a 10% activation chance. Log below.

2024_10_23_22_10_22 Holocure Character Creator Mod v1.0.2 - Finished initializing
2024_10_23_22_10_22 Holocure Menu Mod v1.0.1 - Finished initializing
2024_10_23_22_10_25 Holocure Character Creator Mod v1.0.2 - Loading char_test
2024_10_23_22_10_25 Holocure Character Creator Mod v1.0.2 - Loading char_Zero
2024_10_23_22_10_45  - round argument 1 incorrect type (undefined) expecting a Number (YYGR)
0> CallbackManagerMod__1_!_AurieFrameworkInit+0x2D056
1> HoloCure+0x215C30F
2> HoloCure+0x2182DF1
3> HoloCure+0x2154901
4> HoloCure+0x20AE48C
5> HoloCure+0x2154ABC
6> HoloCure+0x20AC895
7> HoloCure+0x2154ABC
8> HoloCure+0x17EF842
9> HoloCure+0x2154ABC
10> HoloCure+0x20CC43B
11> HoloCure+0x2158EE9
12> YYToolkit!ModuleUnload+0x1E794
13> YYToolkit!ModuleUnload+0x1DEBC
14> CallbackManagerMod__1_!_AurieFrameworkInit+0x2701
15> YYToolkit!ModuleUnload+0x1D4BB
16> YYToolkit!ModuleUnload+0x1C685
17> HoloCure+0x2158963
18> HoloCure+0x22CA8F5
19> HoloCure+0x22B1BFB
20> HoloCure+0x22B1A0D
21> HoloCure+0x22FF787
22> HoloCure+0x22085FF
23> HoloCure+0x22081E3
24> HoloCure+0x2209B8A
25> HoloCure+0x22363EB
26> HoloCure+0x242542E
27> KERNEL32!BaseThreadInitThunk+0x14
28> ntdll!RtlUserThreadStart+0x21

**Comment by PippleCultist** [comment]
This issue should be fixed in v1.0.2
