### ISSUE TITLE
Failed to find memory address for PushContextStack

### ISSUE THREAD

**Issue by CJB256** [PippleCultist/HoloCureCharacterCreatorMod#4]
Hey, so this is probably just me being an idiot somehow, but whenever I try to launch the game with HoloCureCharacterCreatorMod.dll the game crashes a few seconds after launching. CallbackManagerMod.dll and HolocureMenuMod.dll are working fine. The YYToolkit log says a bunch of Firebase modules are failing to load. They're mostly about various types of authentication, so I assume it's unrelated, but I figured I'd mention it.

Holocure folder Log:
2024_11_23_23_19_59 Holocure Character Creator Mod v1.0.2 - Failed to find memory address for PushContextStack
2024_11_23_23_20_00 Holocure Menu Mod v1.0.2 - Finished initializing

Game Version: 0.6.1692569813 [itch version]

**Comment by CJB256** [comment]
After restarting my computer (which I should have done before posting an error report) the game actually launches, though the log still notes that it couldn't find the memory address for PushContextStack. Instead, just before reaching the main menu I get the following error message and the game crashes:
___________________________________________
############################################################################################
ERROR in
action number 1
of Other Event: User Defined 1
for object obj_AttackController:

instance_create_depth argument 2 incorrect type (undefined) expecting a Number (YYGI32)
0> CallbackManagerMod!_AurieFrameworkInit+0x2D056
1> HoloCure+0x2156C03
2> HoloCure+0x218BA66
3> HoloCureCharacterCreatorMod!_AurieFrameworkInit+0x510C6
4> CallbackManagerMod!_AurieFrameworkInit+0x2721
5> YYToolkit!ModuleUnload+0x1D4BB
6> YYToolkit!ModuleUnload+0x1C685
7> HoloCure+0x2153663
8> HoloCure+0x22C55F5
9> HoloCure+0x22AC8FB
10> HoloCure+0x22AC70D
11> HoloCure+0x9517AE
12> HoloCure+0x2153BE9
13> YYToolkit!ModuleUnload+0x1E794
14> YYToolkit!ModuleUnload+0x1DEBC
15> CallbackManagerMod!_AurieFrameworkInit+0x2701
16> YYToolkit!ModuleUnload+0x1D4BB
17> YYToolkit!ModuleUnload+0x1C685
18> HoloCure+0x2153663
19> HoloCure+0x22C55F5
20> HoloCure+0x22AC8FB
21> HoloCure+0x22AC70D
22> HoloCure+0x222B632
23> HoloCure+0x21A20A1
24> HoloCure+0x214F601
25> HoloCure+0x92ABFB
26> HoloCure+0x2153BE9
27> YYToolkit!ModuleUnload+0x1E794
28> YYToolkit!ModuleUnload+0x1DEBC
29> CallbackManagerMod!_AurieFrameworkInit+0x2701
30> YYToolkit!M############################################################################################
gml_Object_obj_AttackController_Create_0 (line 323)
gml_Object_obj_TitleScreen_Create_0 (line 134)

**Comment by PippleCultist** [comment]
I just updated the mod to work with 0.7. Please try it with that and tell me if there are any issues. Also, it's not backwards compatible with 0.6, so you'll need to use it with 0.7.

**Comment by CJB256** [comment]
Wow, you work fast! Whatever the problem was, it's gone in the new version. Thanks for the help.
